name: web-scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20
  - python=3.8
  - pip:
      - scrapy==2.5.0
      - requests==2.25.1
      - urllib3==1.26.4
      - beautifulsoup4==4.9.3
      - selenium==3.141.0
      - webdriver-manager==3.4.0